apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
{{ include "prometheus.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "prometheus.select-labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "prometheus.labels" . | indent 8 }}
    spec:
      containers:
      - image: prom/prometheus:{{ .Values.image.tag }}
        name: prometheus
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention=24h"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: config-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      serviceAccountName: {{ template "prometheus.fullname" . }}
      volumes:
      - name: data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ template "prometheus.fullname" . }}
