apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "web-portal.fullname" . }}
  labels:
{{ include "web-portal.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "web-portal.select-labels" . | indent 8 }}
  template:
    metadata:
      labels:
{{ include "web-portal.labels" . | indent 8 }}
    spec:
{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.image.repository.address }}{{ .Values.global.image.repository.pathname }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}