apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jupyterlab-proxy.fullname" . }}
  labels:
{{ include "jupyterlab-proxy.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "jupyterlab-proxy.select-labels" . | indent 8 }}
  template:
    metadata:
      labels:
{{ include "jupyterlab-proxy.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository.address }}{{ .Values.global.image.repository.pathname }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
          - name: SERVER_PORT
            value: "{{ .Values.service.targetPort }}"
          - name: DefaultTarget
            value: '192.168.202.1'
          ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
