{{- if .Values.ingress.enabled -}}
{{- $fullName := include "jupyterlab-proxy.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "jupyterlab-proxy.labels" . | indent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ $ingressPath }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ .Values.service.port }}
{{- end }}
